# Generated by Django 3.0.6 on 2020-06-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20200601_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
    ]
